#!/usr/bin/env python3

import os
import fire
from dubbing_tools.transcript import Transcript
from dubbing_tools.video import Video
from dubbing_tools.constants import *
from dubbing_tools.functions import *


def cmd(transcript_path: str, lang: str, timing_scheme: str, srt: bool = False,
        overwrite: bool = False, overlay_gain: int = -20):

    transcript = Transcript.load(transcript_path)

    if not os.path.exists(SUBDIR_VIDEO):
        os.makedirs(SUBDIR_VIDEO)

    video = Video(
        source_file=video_source_fullpath(),
        output_path='videos',
        target_file=video_fullpath(lang, timing_scheme),
        # srt_path=os.path.join(project_path, f"phrases-{lang}.srt")
    )

    video.dub_audio(
        transcript=transcript,
        lang=lang,
        timing_scheme=timing_scheme,
        source_audio=os.path.join(SUBDIR_AUDIO, f"source-{timing_scheme}-{lang}.mp3"),
        overwrite=overwrite,
        overlay_gain=overlay_gain,
    )


if __name__ == "__main__":
    fire.Fire(cmd)
