#!/usr/bin/env python3

import fire
from dubbing_tools import *
import sys


def cmd(transcript_path: str, lang: str):
    transcript = Transcript.load(transcript_path)

    transcript.adjust_dub_timings(lang=lang)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
