#!/usr/bin/env python3

import fire
from dubbing_tools import *
from pydub import AudioSegment
from dubbing_tools.constants import *
from dubbing_tools.timings import Timings
from dubbing_tools.functions import *
import os

MARGIN = 5


def cmd(transcript_path: str):
    transcript = Transcript.load(transcript_path)

    audio = AudioSegment.from_file(video_source_fullpath())

    for phrase in transcript.phrases:
        target = phrase.source
        print(f"Id: {phrase.id}  Start: {target.timings.get(Timings.SOURCE).start_time}, End: {target.timings.get(Timings.SOURCE).end_time}  {target.text}")
        clip_start = target.timings.get(Timings.SOURCE).start_time * 1000 - MARGIN
        clip_duration = target.timings.get(Timings.SOURCE).duration() * 1000 + MARGIN
        clip_end = target.timings.get(Timings.SOURCE).end_time * 1000 + MARGIN
        segment = audio[clip_start:clip_end]
        segment.export(target.natural_audio_fullpath(service=SERVICE_SOURCE))


if __name__ == "__main__":
    fire.Fire(cmd)
