#!/usr/bin/env python3

from pydub import AudioSegment
import os
import fire


def cmd(video_file: str, output: str = None):
    if output is None:
        output = os.path.split(video_file)[-1].split('.')[0]

    if not output[-4:] != "wav":
        output += ".wav"

    # TODO: can we output MP3?
    AudioSegment \
        .from_file(video_file) \
        .set_channels(1) \
        .export(output, format="wav")


if __name__ == "__main__":
    fire.Fire(cmd)
