#!/usr/bin/env python3

import fire
from dubbing_tools import *
from dubbing_tools.constants import *
import os


def cmd(transcript_path: str, lang: str, timing_scheme: str, subtitle_lang: str, type: str = 'ass',
        include_source: bool = False, debug: bool = False):
    transcript = Transcript.load(transcript_path)

    transcript.export_subtitles(
        lang=lang,
        timing_scheme=timing_scheme,
        subtitle_lang=subtitle_lang,
        type=type,
        include_source=include_source,
        debug=debug,
    )


if __name__ == "__main__":
    fire.Fire(cmd)
