#!/usr/bin/env python3

import sys
import fire
from dubbing_tools.transcript import *
import dotenv
import csv

dotenv.load_dotenv()


def cmd(transcript_path: str, lang: str):
    transcript = Transcript.load(transcript_path)

    writer = csv.writer(sys.stdout)
    writer.writerows(transcript.to_csv(lang))


if __name__ == "__main__":
    fire.Fire(cmd)
