#!/usr/bin/env python3

import fire
from dubbing_tools.transcript import Transcript

SOURCE_LANG = 'en-US'
SPEAKER_COUNT = 1
PHRASE_HINTS = []


def cmd(project_path: str):
    """
    export manuscript

    Exports a manuscript as a text file with a line for each phrase.

    See manuscript documentation for details on the format (xref:manuscript.adoc[Manuscript Documentation]).

    :param project_path: path to the root of the project directory
    """
    transcript = Transcript.load(project_path)

    print(transcript.to_manuscript())


if __name__ == "__main__":
    fire.Fire(cmd)
