#!/usr/bin/env python3

import fire
from dubbing_tools import *

SOURCE_LANG = 'en-US'
SPEAKER_COUNT = 1
PHRASE_HINTS = []


def cmd(transcript_path: str):
    transcript = Transcript.load(transcript_path)

    print(transcript.to_manuscript())


if __name__ == "__main__":
    fire.Fire(cmd)
