#!/usr/bin/env python3

import sys
import fire
from dubbing_tools.transcript import *
import dotenv
import csv
import codecs
dotenv.load_dotenv()


def cmd(project_path: str, lang: str, utf8_bom: bool = False):
    transcript = Transcript.load(project_path)

    if utf8_bom:
        sys.stdout.write('\xef\xbb\xbf')

    writer = csv.writer(sys.stdout)
    writer.writerows(transcript.to_csv(lang))


if __name__ == "__main__":
    fire.Fire(cmd)
