#!/usr/bin/env python3

import json
import fire
from dubbing_tools.transcript import *


def cmd(project_path: str):
    transcript = Transcript.load(project_path)

    stats = {}

    for i, word in enumerate(transcript.words):
        if i < len(transcript.words)-1:
            gap = str(round(transcript.words[i+1]['start_time'] - word['end_time'], 3))
            if gap in stats:
                stats[gap] += 1
            else:
                stats[gap] = 1

    import pprint
    pprint.pprint(stats)


if __name__ == "__main__":
    fire.Fire(cmd)
