#!/usr/bin/env python3

from dubbing_tools.transcript import Transcript
import fire


SOURCE_LANG = 'en-US'
SPEAKER_COUNT = 1
PHRASE_HINTS = []


def cmd(transcript_path: str, manuscript_file: str):

    transcript = Transcript.load(transcript_path)

    line_num = 0
    with open(manuscript_file, 'r') as f:
        k = 0
        for line in f.readlines():
            line_num += 1

            if len(line.strip()) > 0:
                words = line.split('`')

                j = 0
                while j < len(words):
                    transcript.words[k].manuscript_break_before = j == 0

                    word = transcript.words[k]
                    # if no spaces between the backticks and the words, join them
                    # TODO: this fails if trying to combine more than two words
                    if j < len(words)-1 and words[j][-1] != ' ' and words[j+1][0] != ' ':
                        word.set_word((words[j] + words[j+1]).strip())
                        word.end_time = transcript.words[k+1].end_time
                        del transcript.words[k+1]
                        j += 1

                    else:
                        word.set_word(words[j].strip())

                    j += 1
                    k += 1

    transcript.save()


if __name__ == "__main__":
    fire.Fire(cmd)
