#!/usr/bin/env python3

from dubbing_tools.transcript import *
import sys
import os
import fire


def cmd(project_path: str, srt_file: str, lang: str = 'en'):
    """
    imports SRT file.

    Imports an SRT file which should have one or at most two words per timing entry.

    The words and timings for the given language (default: en) are _REPLACED_ with
    the imported data.

    If `transcript.json.gz` does not exist in the project path it is created.
    """

    transcript = Transcript.load(project_path)
    if transcript is None:
        transcript = Transcript(name=srt_file, src_lang=lang)
        os.makedirs(project_path, exist_ok=True)
        os.chdir(project_path)

    transcript.import_words_srt(srt_file=srt_file)

    if not transcript.save():
        print("Error saving project file.", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
