#!/usr/bin/env python3

from dubbing_tools.transcript import *
import sys
import os
import fire


def cmd(project_path: str, srt_file: str, lang: str = 'en'):
    """
    imports SRT file.

    Imports an SRT file which should have one or at most two words per timing entry.

    The words and timings for the given language (default: en) are *replaced* with
    the imported data and phrases for that language are deleted.  To rebuild the phrases
    run `dt-rebuild-phrases`.

    If `transcript.json.gz` does not exist in the project path it is created.

    :param project_path: path to the root of the project directory
    :param srt_file: name of the SRT file to be imported
    :param lang: language of the imported SRT file
    """

    transcript = Transcript.load(project_path)
    if transcript is None:
        transcript = Transcript(name=srt_file, src_lang=lang, project_path=project_path)
        os.makedirs(project_path, exist_ok=True)

    transcript.import_words_srt(srt_file=srt_file)

    if not transcript.save():
        print("Error saving project file.", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
