#!/usr/bin/env python3

from dubbing_tools.transcript import Transcript
import sys
import os
import fire
import csv
from dataclasses import dataclass


@dataclass
class Combination:
    start: int
    end: int = None


def cmd(project_path: str, lang: str, csv_file: str, combine: bool = False, update_source: bool = False):
    """
    import CSV translation data

    Imports data that has been previously exported using `dt-export-csv` back into the project.

    This operation overwrites the target language translation currently in the project.  Changes to
    timings are discarded.  Source changes are discarded unless the `--update-source` option is used.

    :param project_path: path to the root of the project directory
    :param lang: target language code to be imported from the CSV file
    :param csv_file: name of the CSV file
    :param combine: see documentation
    :param update_source: updates the source language from the CSV.  Use this option with caution
    """

    transcript = Transcript.load(project_path)

    first_id = None
    combinations = []  # type: list[Combination]
    combinator = None

    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if first_id is None:
                first_id = int(row['Id'])
            i = int(row['Id'])-first_id
            print(f"{i} {lang}: {row['Translation']}")
            transcript.phrases[i].set_text(lang, row['Translation'])
            if update_source:
                transcript.phrases[i].source.set_text(row['Source'])

            if combine:
                if 'Combine' in row and row['Combine']:
                    if combinator == row['Combine']:
                        combinations[-1].end = i
                    else:
                        combinations.append(Combination(start=i))
                        combinator = row['Combine']
                else:
                    combinator = None

        while len(combinations):
            combo = combinations.pop()
            transcript.combine_phrases(start_index=combo.start, end_index=combo.end)

    if not transcript.save():
        print("Error saving project file.", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
