#!/usr/bin/env python3

from dubbing_tools.transcript import *
import sys
import os
import fire


def cmd(transcript_path: str, srt_file: str, lang: str = 'en'):
    """Import SRT file as new words with times.  Should only have one word per line."""

    transcript = Transcript.load(transcript_path)
    if transcript is None:
        transcript = Transcript(name=srt_file, src_lang=lang)
        os.makedirs(transcript_path, exist_ok=True)
        os.chdir(transcript_path)

    transcript.import_words_srt(srt_file=srt_file)

    if not transcript.save():
        print("Error saving project file.", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
