#!/usr/bin/env python3

from dubbing_tools import *
import sys
import os
import fire


def cmd(transcript_path: str, lang: str, ids: list):

    transcript = Transcript.load(transcript_path)

    for id in ids:
        print(f"Id: {id}")
        transcript.phrases[id].get_target(lang).mark_audio_changed()

    if not transcript.save():
        print("Error saving project file.", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
