#!/usr/bin/env python3

import fire
from dubbing_tools.transcript import *
import sys


def cmd(project_path: str, gap: float = 1.0, mark_breaks: bool = False):
    transcript = Transcript.load(project_path)

    transcript.compute_phrases(gap=gap, mark_breaks=mark_breaks)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
