#!/usr/bin/env python3

import fire
from dubbing_tools.transcript import *
import sys


def cmd(project_path: str, mark_breaks: bool = True, gap: float = 1.0):
    """
    rebuild phrases for the source language

    Rebuilds phrases for the source language from the words with timings.

    :param project_path: path to the root of the project directory
    :param mark_breaks: mark the phrase breaks in the words list
    :param gap: value in seconds to use for splitting phrases
    """
    transcript = Transcript.load(project_path)

    transcript.compute_phrases(gap=gap, mark_breaks=mark_breaks)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
