#!/usr/bin/env python3

import fire
from dubbing_tools.transcript import *
import sys
import dotenv
from dubbing_tools.constants import *

dotenv.load_dotenv()


def cmd(project_path: str, lang: str, timing_scheme: str, service: str, overwrite: bool = False):
    if service not in [SERVICE_AZURE, SERVICE_GOOGLE]:
        print(f"Unknown service: {service}", file=sys.stderr)

    if timing_scheme not in Timings.SCHEMES:
        print(f"Unknown timing scheme: {timing_scheme}", file=sys.stderr)

    transcript = Transcript.load(project_path)

    transcript.get_tts_duration_audio(
        lang=lang,
        timing_scheme=timing_scheme,
        service=service,
        overwrite=overwrite
    )

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
