#!/usr/bin/env python3

import sys
import os
import fire
from dubbing_tools.transcript import *
import dotenv

if not dotenv.load_dotenv(dotenv_path=os.path.join(os.getcwd(), '.env')):
    if not dotenv.load_dotenv(dotenv_path=os.environ['HOME']):
        print('credentials not found in %s' % str([os.getcwd(), os.environ['HOME']]), file=sys.stderr)
        exit(2)


def cmd(transcript_path: str, to_lang: str):
    transcript = Transcript.load(transcript_path)
    for phrase in transcript.phrases:
        phrase.translate_text(to_lang)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
