#!/usr/bin/env python3

import sys
import os
import fire
from dubbing_tools.transcript import *
import dotenv


def cmd(project_path: str, to_lang: str):
    if not dotenv.load_dotenv(dotenv_path=os.path.join(os.getcwd(), '.dubbing_tools')):
        if not dotenv.load_dotenv(dotenv_path=os.path.join(os.environ['HOME'], '.config', 'dubbing_tools')):
            print('credentials not found in %s' % str([os.getcwd(), os.environ['HOME']]), file=sys.stderr)
            exit(2)

    transcript = Transcript.load(project_path)
    for phrase in transcript.phrases:
        phrase.translate_text(to_lang)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
