#!/usr/bin/env python3

import re
import fire


def cmd(otter_transcript: str):
    f = open(otter_transcript, mode='r')

    num = 0
    start = 0.0
    end = 0.0
    duration = 0.0
    for line in f.readlines():
        line = line.strip()

        if re.match(r'\d+$', line):
            continue

        m = re.search(r'(\d+):(\d+):(\d+),(\d+)\s* -->\s*(\d+):(\d+):(\d+),(\d+)', line)
        if m:
            start = float(int(m[1]) * 360 + int(m[2]) * 60 + int(m[3])) + float(m[4]) / 1000
            end = float(int(m[5]) * 360 + int(m[6]) * 60 + int(m[7])) + float(m[8]) / 1000
            duration = round(end - start, 3)

        else:
            words = line.split(' ')
            if len(words) > 1 and words[0] not in ('in', 'at', 'as', 'and', 'of', 'to', 'So') and duration > 0.5:
                num += 1
                print(f"{str(num).rjust(3)}: {line.ljust(20)} {str(start).rjust(8)}  {str(duration).rjust(6)}")

        # matches = re.findall(r'(^|\s)(?P<words>\w{1,2}\s\w{1,2}|\w{3}\s\w|\w\s\w{3})(\s|$)', line)
        # for match in matches:
        #     num += 1
        #     print(f"{num}: {match[1]} {duration}")


if __name__ == "__main__":
    fire.Fire(cmd)
