#!/usr/bin/env python3

import fire
from classes import *
import sys
import dotenv

dotenv.load_dotenv()


def cmd(transcript_path: str, lang: str, overwrite: bool = False):
    transcript = Transcript.load(transcript_path)

    transcript.get_tts_natural_audio(lang=lang, overwrite=overwrite)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
