#!/usr/bin/env python3

import fire
from classes import *
from pydub import AudioSegment
from classes.constants import *
from classes.timings import Timings

MARGIN = 5


def cmd(transcript_path: str,  video_file: str):
    transcript = Transcript.load(transcript_path)

    audio = AudioSegment.from_file(video_file)

    for phrase in transcript.phrases:
        target = phrase.source
        print(f"Id: {phrase.id}  Start: {target.timings.get(Timings.TIMING_SOURCE).start_time}, End: {target.timings.get(Timings.TIMING_SOURCE).end_time}  {target.text}")
        clip_start = target.timings.get(Timings.TIMING_SOURCE).start_time*1000-MARGIN
        clip_duration = target.timings.get(Timings.TIMING_SOURCE).duration()*1000+MARGIN
        clip_end = target.timings.get(Timings.TIMING_SOURCE).end_time * 1000 + MARGIN
        segment = audio[clip_start:clip_end]
        segment.export(target.natural_audio_fullpath(service=SERVICE_SOURCE))


if __name__ == "__main__":
    fire.Fire(cmd)
