#!/usr/bin/env python3

import fire
from classes import *
import sys
import dotenv
from classes.constants import *

dotenv.load_dotenv()


def cmd(transcript_path: str, lang: str, service: str, overwrite: bool = False):
    if service not in [SERVICE_AZURE, SERVICE_GOOGLE]:
        print(f"Unknown service: {service}", file=sys.stderr)

    transcript = Transcript.load(transcript_path)

    transcript.get_tts_natural_audio(lang=lang, service=service, overwrite=overwrite)

    if not transcript.save():
        print("Error saving transcript", file=sys.stderr)


if __name__ == "__main__":
    fire.Fire(cmd)
