= Documentation
:icons: font
:toc:

== Introduction

An eleven minute segment from Dr. Beeke's first lecture on Soteriology was chosen as a test for evaluating the best way to translate a video lecture.  Our goals in this test are:

1. Determine the work involved in subtitling and dubbing a lecture into Arabic

2. Get feedback from prospective students on their preference for dubbing or subtitles.

== Process

The basic process we have so far defined is as follows:

1. Use speech-to-text (STT) technology to create an English transcription of the lecture (with timings for when each word was spoken).

2. Edit the transcription while maintaining word timings.

3. Break the transcription into phrases for subtitles.

4. Use AI Machine translation to translate the phrases into Arabic.

5. Review and edit the Arabic translation.

6. Create English video with Arabic subtitles.

7. Use text-to-speech (TTS) technology to create Arabic audio of the translations.

8. Create Arabic video with English subtitles.


[#STT]
=== Speech-to-Text (STT)

We tried two different services for speech-to-text conversion: Otter (https://otter.ai) and Google (https://cloud.google.com/translate/).

* Otter -- Otter is not able to export word timings and its export of subtitles is based on letters perl line.  It does not take into account pauses between phrases which is the normal way to create phrases for subtitles.  It has a very nice interface for editing the transcripts created from STT but its poor export options seem to make it a bad choice.

* Google -- Google provides word timings and our initial test used Google for AI manuscript creation.

Below is an example of data generated by STT systems.  Each word is listed with the timings for when the speaker began to speak the word (`startTime`) and when he finished (`endTime`).

[source, json]
----
{
  "words": [
    {
      "confidence": 0.91283858,
      "endTime": "1.400s",
      "startTime": "1.200s",
      "word": "Well,"
    },
    {
      "confidence": 0.91283858,
      "endTime": "1.800s",
      "startTime": "1.400s",
      "word": "welcome"
    },
    {
      "confidence": 0.91283858,
      "endTime": "2.300s",
      "startTime": "1.800s",
      "word": "to"
    },
    {
      "confidence": 0.91283858,
      "endTime": "3.600s",
      "startTime": "2.300s",
      "word": "soteriology"
    }
  ]
}
----

The initial evaluation of Google STT was positive but it struggles in a few areas:

1. It gets confused by King James English -- improvement in this area may be possible by providing the STT service with a glossary.

2. Sometimes confused by similar sounding words (e.g. confuses _soul_ and _sole_)

3. Does not understand verse references with colons properly (e.g. transcribes _Romans 8:13 through 17_ as _Romans 813 through 17_)

NOTE: Microsoft and Amazon also provide STT services.  Given the superiority of Microsoft's TTS voices (<<TTS,see below>>) their STT service should be evaluated.  Amazon STT could also be evaluated but their TTS is not as advanced as Microsoft's TTS.


=== English Transcription Editing

The text manuscript was edited to fix errors in the STT and to add punctuation that is useful in breaking the manuscript into phrases.


[#TTS]
=== Text-to-Speech (TTS)


== Programs

===
