# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/dlg_export_subtitles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgExportSubtitles(object):
    def setupUi(self, DlgExportSubtitles):
        DlgExportSubtitles.setObjectName("DlgExportSubtitles")
        DlgExportSubtitles.resize(322, 172)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgExportSubtitles)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DlgExportSubtitles)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmbLanguage = QtWidgets.QComboBox(DlgExportSubtitles)
        self.cmbLanguage.setObjectName("cmbLanguage")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbLanguage)
        self.label_2 = QtWidgets.QLabel(DlgExportSubtitles)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cmbTimingScheme = QtWidgets.QComboBox(DlgExportSubtitles)
        self.cmbTimingScheme.setObjectName("cmbTimingScheme")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbTimingScheme)
        self.label_3 = QtWidgets.QLabel(DlgExportSubtitles)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbSubtitleLanguage = QtWidgets.QComboBox(DlgExportSubtitles)
        self.cmbSubtitleLanguage.setObjectName("cmbSubtitleLanguage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbSubtitleLanguage)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgExportSubtitles)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgExportSubtitles)
        self.buttonBox.accepted.connect(DlgExportSubtitles.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgExportSubtitles.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgExportSubtitles)

    def retranslateUi(self, DlgExportSubtitles):
        _translate = QtCore.QCoreApplication.translate
        DlgExportSubtitles.setWindowTitle(_translate("DlgExportSubtitles", "Export Subtitles"))
        self.label.setText(_translate("DlgExportSubtitles", "Language"))
        self.label_2.setText(_translate("DlgExportSubtitles", "Timing Scheme"))
        self.label_3.setText(_translate("DlgExportSubtitles", "Subtitle Language"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgExportSubtitles = QtWidgets.QDialog()
    ui = Ui_DlgExportSubtitles()
    ui.setupUi(DlgExportSubtitles)
    DlgExportSubtitles.show()
    sys.exit(app.exec_())
