# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/dlg_delete_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDeleteLanguage(object):
    def setupUi(self, DlgDeleteLanguage):
        DlgDeleteLanguage.setObjectName("DlgDeleteLanguage")
        DlgDeleteLanguage.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDeleteLanguage.resize(322, 102)
        self.formLayout_2 = QtWidgets.QFormLayout(DlgDeleteLanguage)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DlgDeleteLanguage)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmbLanguage = QtWidgets.QComboBox(DlgDeleteLanguage)
        self.cmbLanguage.setObjectName("cmbLanguage")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbLanguage)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgDeleteLanguage)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.buttonBox)

        self.retranslateUi(DlgDeleteLanguage)
        self.buttonBox.accepted.connect(DlgDeleteLanguage.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgDeleteLanguage.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgDeleteLanguage)

    def retranslateUi(self, DlgDeleteLanguage):
        _translate = QtCore.QCoreApplication.translate
        DlgDeleteLanguage.setWindowTitle(_translate("DlgDeleteLanguage", "Delete Language"))
        self.label.setText(_translate("DlgDeleteLanguage", "Language"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDeleteLanguage = QtWidgets.QDialog()
    ui = Ui_DlgDeleteLanguage()
    ui.setupUi(DlgDeleteLanguage)
    DlgDeleteLanguage.show()
    sys.exit(app.exec_())
