# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/dlg_burn_subtitles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgBurnSubtitles(object):
    def setupUi(self, DlgBurnSubtitles):
        DlgBurnSubtitles.setObjectName("DlgBurnSubtitles")
        DlgBurnSubtitles.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgBurnSubtitles.resize(715, 488)
        DlgBurnSubtitles.setModal(True)
        self.widget = QtWidgets.QWidget(DlgBurnSubtitles)
        self.widget.setGeometry(QtCore.QRect(10, 12, 691, 461))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmbLanguage = QtWidgets.QComboBox(self.widget)
        self.cmbLanguage.setObjectName("cmbLanguage")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbLanguage)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cmbTimingScheme = QtWidgets.QComboBox(self.widget)
        self.cmbTimingScheme.setObjectName("cmbTimingScheme")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbTimingScheme)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbSubtitleLanguage = QtWidgets.QComboBox(self.widget)
        self.cmbSubtitleLanguage.setObjectName("cmbSubtitleLanguage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbSubtitleLanguage)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbtBurnSubtitles = QtWidgets.QPushButton(self.widget)
        self.pbtBurnSubtitles.setEnabled(False)
        self.pbtBurnSubtitles.setObjectName("pbtBurnSubtitles")
        self.verticalLayout.addWidget(self.pbtBurnSubtitles)
        self.pbtCancel = QtWidgets.QPushButton(self.widget)
        self.pbtCancel.setObjectName("pbtCancel")
        self.verticalLayout.addWidget(self.pbtCancel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lneProgress = QtWidgets.QLineEdit(self.widget)
        self.lneProgress.setObjectName("lneProgress")
        self.verticalLayout_2.addWidget(self.lneProgress)
        self.pteLog = QtWidgets.QPlainTextEdit(self.widget)
        self.pteLog.setObjectName("pteLog")
        self.verticalLayout_2.addWidget(self.pteLog)

        self.retranslateUi(DlgBurnSubtitles)
        QtCore.QMetaObject.connectSlotsByName(DlgBurnSubtitles)

    def retranslateUi(self, DlgBurnSubtitles):
        _translate = QtCore.QCoreApplication.translate
        DlgBurnSubtitles.setWindowTitle(_translate("DlgBurnSubtitles", "Dialog"))
        self.label.setText(_translate("DlgBurnSubtitles", "Language"))
        self.label_2.setText(_translate("DlgBurnSubtitles", "Timing Scheme"))
        self.label_3.setText(_translate("DlgBurnSubtitles", "Subtitle Language"))
        self.pbtBurnSubtitles.setText(_translate("DlgBurnSubtitles", "Burn Subtitles"))
        self.pbtCancel.setText(_translate("DlgBurnSubtitles", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgBurnSubtitles = QtWidgets.QDialog()
    ui = Ui_DlgBurnSubtitles()
    ui.setupUi(DlgBurnSubtitles)
    DlgBurnSubtitles.show()
    sys.exit(app.exec_())
