# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(806, 607)
        self.centralwidget = QtWidgets.QWidget(WindowMain)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 781, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lneProjectPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneProjectPath.setEnabled(False)
        self.lneProjectPath.setReadOnly(True)
        self.lneProjectPath.setObjectName("lneProjectPath")
        self.horizontalLayout.addWidget(self.lneProjectPath)
        self.pbSelectProject = QtWidgets.QPushButton(self.layoutWidget)
        self.pbSelectProject.setObjectName("pbSelectProject")
        self.horizontalLayout.addWidget(self.pbSelectProject)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.leLanguagesList = QtWidgets.QLineEdit(self.layoutWidget)
        self.leLanguagesList.setEnabled(False)
        self.leLanguagesList.setObjectName("leLanguagesList")
        self.horizontalLayout_3.addWidget(self.leLanguagesList)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        WindowMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 24))
        self.menubar.setObjectName("menubar")
        self.menuOpenProject = QtWidgets.QMenu(self.menubar)
        self.menuOpenProject.setObjectName("menuOpenProject")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        WindowMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowMain)
        self.statusbar.setObjectName("statusbar")
        WindowMain.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(WindowMain)
        self.toolBar.setObjectName("toolBar")
        WindowMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenProject = QtWidgets.QAction(WindowMain)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionQuit = QtWidgets.QAction(WindowMain)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopyLanguage = QtWidgets.QAction(WindowMain)
        self.actionCopyLanguage.setObjectName("actionCopyLanguage")
        self.actionExportSubtitles = QtWidgets.QAction(WindowMain)
        self.actionExportSubtitles.setObjectName("actionExportSubtitles")
        self.actionDeleteLanguage = QtWidgets.QAction(WindowMain)
        self.actionDeleteLanguage.setObjectName("actionDeleteLanguage")
        self.menuOpenProject.addAction(self.actionOpenProject)
        self.menuOpenProject.addSeparator()
        self.menuOpenProject.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionCopyLanguage)
        self.menuTools.addAction(self.actionDeleteLanguage)
        self.menuTools.addAction(self.actionExportSubtitles)
        self.menubar.addAction(self.menuOpenProject.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(WindowMain)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "Dubbing Tools"))
        self.label.setText(_translate("WindowMain", "Project"))
        self.pbSelectProject.setText(_translate("WindowMain", "Select"))
        self.label_2.setText(_translate("WindowMain", "Languages"))
        self.menuOpenProject.setTitle(_translate("WindowMain", "&File"))
        self.menuTools.setTitle(_translate("WindowMain", "Tools"))
        self.toolBar.setWindowTitle(_translate("WindowMain", "toolBar"))
        self.actionOpenProject.setText(_translate("WindowMain", "Open Project"))
        self.actionQuit.setText(_translate("WindowMain", "Quit"))
        self.actionCopyLanguage.setText(_translate("WindowMain", "Copy Language"))
        self.actionExportSubtitles.setText(_translate("WindowMain", "Export subtitles"))
        self.actionDeleteLanguage.setText(_translate("WindowMain", "Delete Language"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowMain = QtWidgets.QMainWindow()
    ui = Ui_WindowMain()
    ui.setupUi(WindowMain)
    WindowMain.show()
    sys.exit(app.exec_())
